In [ ]:
import numpy as np

# Initial mask, overlay, and image
mask = np.array([
    [0, 1, 1],
    [0, 0, 1],
    [1, 0, 0]
])

overlay = np.array([[[0, 0, 0], [0, 0, 0], [0, 0, 0]],
                    [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
                    [[0, 0, 0], [0, 0, 0], [0, 0, 0]]], dtype=np.uint8)

image = np.array([
    [[255,   0,   0], 
     [  0, 255,   0], 
     [  0,   0, 255]],
    [[255, 255,   0], 
     [  0, 255, 255], 
     [255,   0, 255]],
    [[128, 128, 128], 
     [ 64,  64,  64], 
     [192, 192, 192]]
], dtype=np.uint8)

alpha = 0.5
class_colors = {
    0: (0, 0, 0),
    1: [255, 255, 0]
}

print("Before Overlay ==> ", overlay)

# Apply class colors to overlay
for class_id, color in class_colors.items():
    if class_id == 0:
        continue  # Skip background
    class_mask = (mask == class_id)
    print("Class Mask ==> ", class_mask)
    overlay[class_mask] = color

# Extract channels
R = overlay[..., 0]
G = overlay[..., 1]
B = overlay[..., 2]

print("Overlay Red Channel ==> ", R)
print("Overlay Green Channel ==> ", G)  
print("Overlay Blue Channel ==> ", B)
print("After Overlay ==> ", overlay)

# Blend image and overlay
blended_image = image.copy()

# Create a mask where any class ≠ 0
object_mask = (mask == 1)
print("Object mask ==> ", object_mask)

# blended_image[object_mask] = (
#     image[object_mask] * (1 - alpha) + overlay[object_mask] * alpha
# ).astype(np.uint8)
    
blended_image[object_mask] = cv2.addWeighted(
        image[object_mask], 1 - alpha, overlay[object_mask], alpha, 0
    )

print("Blended Image ==> ", blended_image)



Before Overlay ==>  [[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
Class Mask ==>  [[False  True  True]
 [False False  True]
 [ True False False]]
Overlay Red Channel ==>  [[  0 255 255]
 [  0   0 255]
 [255   0   0]]
Overlay Green Channel ==>  [[  0 255 255]
 [  0   0 255]
 [255   0   0]]
Overlay Blue Channel ==>  [[0 0 0]
 [0 0 0]
 [0 0 0]]
After Overlay ==>  [[[  0   0   0]
  [255 255   0]
  [255 255   0]]

 [[  0   0   0]
  [  0   0   0]
  [255 255   0]]

 [[255 255   0]
  [  0   0   0]
  [  0   0   0]]]
Object mask ==>  [[False  True  True]
 [False False  True]
 [ True False False]]
Blended Image ==>  [[[255   0   0]
  [127 255   0]
  [127 127 127]]

 [[255 255   0]
  [  0 255 255]
  [255 127 127]]

 [[191 191  64]
  [ 64  64  64]
  [192 192 192]]]
